version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: vehicle_management:latest
    restart: always
    ports:
      - "8080:9094"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring
      - SPRING_DATASOURCE_USERNAME=postgres

      - SPRING_DATASOURCE_PASSWORD=angele
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on: # In swarm mode, healthchecks are a better way to manage startup order
      - db
      - redis
    networks:
      - vehicles-network


  # Load balancer service
  nginx:
    image: nginx:latest

    ports:
      - "8080:80"
    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - vehicles-network

  # Database service
  db:
    image: postgres:14

    environment:
      - POSTGRES_DB=vehicles
      - POSTGRES_USER=postgres

      - POSTGRES_PASSWORD=postgres
    volumes:

      - postgres-data:/var/lib/postgresql/data
    networks:
      - vehicles-network

  # Redis service
  redis:
    image: redis:7

    volumes:
      - redis-data:/data
    networks:
      - vehicles-network

# Volumes for persistent data
volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

# Network for all services
networks:
  vehicles-network:
    driver: overlay

