# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=angele
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.session.jdbc.initialize-schema=always
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

# Redis configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=
spring.cache.type=redis

# Admin user
admin.email=amrieangele@gmail.com
admin.password=Angele@2025

# JWT configuration
jwt.secret=0e9f0a8546b36b85cdeb77b7f1742f9989b02cca80b33a63614dc407d67187e9586072d816392bf7101885cb9736b6a63e454159db3cc70fbf7ffeee3fab60a8
jwt.expiresIn=86400000

# Tomcat server
spring.mvc.async.request-timeout=1000000ms
server.tomcat.connection-timeout=1000000ms

# File upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework.boot=INFO

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asifiwemarie2006@gmail.com
spring.mail.password=wumuwrvhqdwbsvfr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp

# Overall health and metrics
management.endpoints.web.exposure.include=health,info,prometheus

# Rate limiting configuration
resilience4j.ratelimiter.instances.auth-rate-limiter.limit-for-period=10
resilience4j.ratelimiter.instances.auth-rate-limiter.limit-refresh-period=30s
resilience4j.ratelimiter.instances.auth-rate-limiter.timeout-duration=100ms

resilience4j.ratelimiter.instances.otp-rate-limiter.limit-for-period=2
resilience4j.ratelimiter.instances.otp-rate-limiter.limit-refresh-period=10m
resilience4j.ratelimiter.instances.otp-rate-limiter.timeout-duration=100ms